#
# Component Makefile
#
#

COMPONENT_INCLUDE_DIRS :=																											\
							components/pal-platform/Device																			\
							components/pal-platform																					\
							components/pal-platform/Middleware																		\
							components/mbed-cloud-client																			\
							components/mbed-cloud-client/source																		\					
							components/mbed-cloud-client/mbed-client																\
							components/mbed-cloud-client/mbed-client/mbed-client-mbed-tls											\
							components/mbed-cloud-client/mbed-client/mbed-client-classic											\
							components/mbed-cloud-client/mbed-client/source															\
							components/mbed-cloud-client/certificate-enrollment-client												\
							components/mbed-cloud-client/certificate-enrollment-client/source										\
							components/mbed-cloud-client/mbed-client-pal															\
							components/mbed-cloud-client/mbed-client-pal/Utils														\
							components/mbed-cloud-client/mbed-client-pal/Utils/stackUsage											\
							components/mbed-cloud-client/mbed-client-pal/Source/Port												\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/PlatformAPI									\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl									\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Lib_Specific					\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Lib_specific/mbedTLS			\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic							\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/Entropy					\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/SST						\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/DRBG					\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/ROT						\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/Storage					\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/Storage/Flash			\
							components/mbed-cloud-client/mbed-client-pal/Source														\
							components/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl											\
							components/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Modules									\
							components/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Services-API								\
							components/mbed-cloud-client/mbed-client-pal/Configs													\
							components/mbed-cloud-client/mbed-client-pal/Configs/pal_config/FreeRTOS								\
							components/mbed-cloud-client/factory-configurator-client												\
							components/mbed-cloud-client/factory-configurator-client/fcc-output-info-handler						\
							components/mbed-cloud-client/factory-configurator-client/ftcd-comm-base									\
							components/mbed-cloud-client/factory-configurator-client/ftcd-comm-socket								\
							components/mbed-cloud-client/factory-configurator-client/ftcd-comm-serial								\
							components/mbed-cloud-client/factory-configurator-client/factory-configurator-client					\
							components/mbed-cloud-client/factory-configurator-client/storage										\
							components/mbed-cloud-client/factory-configurator-client/mbed-client-esfs								\
							components/mbed-cloud-client/factory-configurator-client/mbed-client-esfs/source						\
							components/mbed-cloud-client/factory-configurator-client/crypto-service									\
							components/mbed-cloud-client/factory-configurator-client/utils											\
							components/mbed-cloud-client/factory-configurator-client/key-config-manager								\
							components/mbed-cloud-client/factory-configurator-client/mbed-trace-helper								\
							components/mbed-cloud-client/factory-configurator-client/psa-driver										\
							components/mbed-cloud-client/factory-configurator-client/fcc-bundle-handler								\
							components/mbed-cloud-client/update-client-hub															\
							components/mbed-cloud-client/update-client-hub/delta-tool-internal										\
							components/mbed-cloud-client/update-client-hub/modules													\
							components/mbed-cloud-client/update-client-hub/modules/firmware-manager									\
							components/mbed-cloud-client/update-client-hub/modules/source-http-socket								\
							components/mbed-cloud-client/update-client-hub/modules/device-identity									\
							components/mbed-cloud-client/update-client-hub/modules/manifest-manager									\
							components/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed										\
							components/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/update-client-lwm2m					\
							components/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source								\
							components/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source								\
							components/mbed-cloud-client/update-client-hub/modules/pal-target-specific								\
							components/mbed-cloud-client/update-client-hub/modules/pal-flashiap										\
							components/mbed-cloud-client/update-client-hub/modules/pal-flashiap/update-client-pal-flashiap			\
							components/mbed-cloud-client/update-client-hub/modules/pal-flashiap/source								\
							components/mbed-cloud-client/update-client-hub/modules/common											\
							components/mbed-cloud-client/update-client-hub/modules/common/update-client-common						\
							components/mbed-cloud-client/update-client-hub/modules/common/source									\
							components/mbed-cloud-client/update-client-hub/modules/metadata-header									\
							components/mbed-cloud-client/update-client-hub/modules/metadata-header/update-client-metadata-header	\
							components/mbed-cloud-client/update-client-hub/modules/metadata-header/source							\
							components/mbed-cloud-client/update-client-hub/modules/pal-linux										\
							components/mbed-cloud-client/update-client-hub/modules/pal-linux/scripts								\
							components/mbed-cloud-client/update-client-hub/modules/pal-linux/scripts/openwrt						\
							components/mbed-cloud-client/update-client-hub/modules/pal-linux/scripts/generic						\
							components/mbed-cloud-client/mbed-coap																	\
							components/mbed-cloud-client/mbed-coap/mbed-coap														\
							components/mbed-cloud-client/mbed-coap/source															\
							components/mbed-cloud-client/ns-hal-pal																	\
							components/mbed-cloud-client/mbed-cloud-client															\
							components/mbed-cloud-client/sal-stack-nanostack-eventloop												\
							components/mbed-cloud-client/sal-stack-nanostack-eventloop/source										\
							components/mbed-cloud-client/mbed-trace																	\
							components/mbed-cloud-client/secure-device-access-client												\
							components/mbed-cloud-client/secure-device-access-client/cose-c											\
							components/mbed-cloud-client/secure-device-access-client/secure-device-access							\
							components/mbed-cloud-client/secure-device-access-client/sda-cose										\
							components/mbed-cloud-client/secure-device-access-client/sda-cose/sda-cose								\
							components/mbed-cloud-client/secure-device-access-client/sda-cose/source								\
							components/mbed-cloud-client/secure-device-access-client/helpers										\
							components/mbed-cloud-client/secure-device-access-client/helpers/helpers								\
							components/mbed-cloud-client/secure-device-access-client/helpers/source									\
							components/mbed-cloud-client/secure-device-access-client/logger											\
							components/mbed-cloud-client/secure-device-access-client/logger/logger									\
							components/mbed-cloud-client/secure-device-access-client/logger/sources									\
							components/mbed-cloud-client/secure-device-access-client/mem											\
							components/mbed-cloud-client/secure-device-access-client/sda-bundle-parser								\
							components/mbed-cloud-client/nanostack-libservice														\
							components/source																						\
							components/source/platform

COMPONENT_INCLUDE_DIRS :=																											\
							components/pal-platform/Device																			\
							components/pal-platform																					\
							components/pal-platform/Middleware																		\
							components/mbed-cloud-client																			\
							components/mbed-cloud-client/mbed-client																\
							components/mbed-cloud-client/mbed-client/mbed-client-mbed-tls											\
							components/mbed-cloud-client/mbed-client/mbed-client-classic											\
							components/mbed-cloud-client/mbed-client/source															\
							components/mbed-cloud-client/certificate-enrollment-client												\
							components/mbed-cloud-client/certificate-enrollment-client/source										\
							components/mbed-cloud-client/mbed-client-pal															\
							components/mbed-cloud-client/mbed-client-pal/Utils														\
							components/mbed-cloud-client/mbed-client-pal/Utils/stackUsage											\
							components/mbed-cloud-client/mbed-client-pal/Source/Port												\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/PlatformAPI									\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl									\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Lib_Specific					\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Lib_specific/mbedTLS			\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic							\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/Entropy					\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/SST						\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/DRBG					\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/ROT						\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/Storage					\
							components/mbed-cloud-client/mbed-client-pal/Source/Port/Reference-Impl/Generic/Storage/Flash			\
							components/mbed-cloud-client/mbed-client-pal/Source														\
							components/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl											\
							components/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Modules									\
							components/mbed-cloud-client/mbed-client-pal/Source/PAL-Impl/Services-API								\
							components/mbed-cloud-client/mbed-client-pal/Configs													\
							components/mbed-cloud-client/mbed-client-pal/Configs/pal_config/FreeRTOS								\
							components/mbed-cloud-client/factory-configurator-client												\
							components/mbed-cloud-client/factory-configurator-client/fcc-output-info-handler						\
							components/mbed-cloud-client/factory-configurator-client/ftcd-comm-base									\
							components/mbed-cloud-client/factory-configurator-client/ftcd-comm-socket								\
							components/mbed-cloud-client/factory-configurator-client/ftcd-comm-serial								\
							components/mbed-cloud-client/factory-configurator-client/factory-configurator-client					\
							components/mbed-cloud-client/factory-configurator-client/storage										\
							components/mbed-cloud-client/factory-configurator-client/mbed-client-esfs								\
							components/mbed-cloud-client/factory-configurator-client/mbed-client-esfs/source						\
							components/mbed-cloud-client/factory-configurator-client/crypto-service									\
							components/mbed-cloud-client/factory-configurator-client/utils											\
							components/mbed-cloud-client/factory-configurator-client/key-config-manager								\
							components/mbed-cloud-client/factory-configurator-client/mbed-trace-helper								\
							components/mbed-cloud-client/factory-configurator-client/psa-driver										\
							components/mbed-cloud-client/factory-configurator-client/fcc-bundle-handler								\
							components/mbed-cloud-client/update-client-hub															\
							components/mbed-cloud-client/update-client-hub/delta-tool-internal										\
							components/mbed-cloud-client/update-client-hub/modules													\
							components/mbed-cloud-client/update-client-hub/modules/firmware-manager									\
							components/mbed-cloud-client/update-client-hub/modules/source-http-socket								\
							components/mbed-cloud-client/update-client-hub/modules/device-identity									\
							components/mbed-cloud-client/update-client-hub/modules/manifest-manager									\
							components/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed										\
							components/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/update-client-lwm2m					\
							components/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source								\
							components/mbed-cloud-client/update-client-hub/modules/lwm2m-mbed/source								\
							components/mbed-cloud-client/update-client-hub/modules/pal-target-specific								\
							components/mbed-cloud-client/update-client-hub/modules/pal-flashiap										\
							components/mbed-cloud-client/update-client-hub/modules/pal-flashiap/update-client-pal-flashiap			\
							components/mbed-cloud-client/update-client-hub/modules/pal-flashiap/source								\
							components/mbed-cloud-client/update-client-hub/modules/common											\
							components/mbed-cloud-client/update-client-hub/modules/common/update-client-common						\
							components/mbed-cloud-client/update-client-hub/modules/common/source									\
							components/mbed-cloud-client/update-client-hub/modules/metadata-header									\
							components/mbed-cloud-client/update-client-hub/modules/metadata-header/update-client-metadata-header	\
							components/mbed-cloud-client/update-client-hub/modules/metadata-header/source							\
							components/mbed-cloud-client/update-client-hub/modules/pal-linux										\
							components/mbed-cloud-client/update-client-hub/modules/pal-linux/scripts								\
							components/mbed-cloud-client/update-client-hub/modules/pal-linux/scripts/openwrt						\
							components/mbed-cloud-client/update-client-hub/modules/pal-linux/scripts/generic						\
							components/mbed-cloud-client/mbed-coap																	\
							components/mbed-cloud-client/mbed-coap/mbed-coap														\
							components/mbed-cloud-client/mbed-coap/source															\
							components/mbed-cloud-client/ns-hal-pal																	\
							components/mbed-cloud-client/mbed-cloud-client															\
							components/mbed-cloud-client/sal-stack-nanostack-eventloop												\
							components/mbed-cloud-client/sal-stack-nanostack-eventloop/source										\
							components/mbed-cloud-client/mbed-trace																	\
							components/mbed-cloud-client/secure-device-access-client												\
							components/mbed-cloud-client/secure-device-access-client/cose-c											\
							components/mbed-cloud-client/secure-device-access-client/secure-device-access							\
							components/mbed-cloud-client/secure-device-access-client/sda-cose										\
							components/mbed-cloud-client/secure-device-access-client/sda-cose/sda-cose								\
							components/mbed-cloud-client/secure-device-access-client/sda-cose/source								\
							components/mbed-cloud-client/secure-device-access-client/helpers										\
							components/mbed-cloud-client/secure-device-access-client/helpers/helpers								\
							components/mbed-cloud-client/secure-device-access-client/helpers/source									\
							components/mbed-cloud-client/secure-device-access-client/logger											\
							components/mbed-cloud-client/secure-device-access-client/logger/logger									\
							components/mbed-cloud-client/secure-device-access-client/logger/sources									\
							components/mbed-cloud-client/secure-device-access-client/mem											\
							components/mbed-cloud-client/secure-device-access-client/sda-bundle-parser								\
							components/mbed-cloud-client/source																		\
							components/mbed-cloud-client/nanostack-libservice														\
							components/source																						\
							components/source/platform

#COMPONENT_SUBMODULES :=	components

CXXFLAGS +=	 -D__FREERTOS__												\
		 	 -DMBED_CONF_NS_HAL_PAL_EVENT_LOOP_THREAD_STACK_SIZE=8192	\

